/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-09 08:19:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <!--<link rel=\"icon\" href=\"img/favicon.ico\">-->\r\n");
      out.write("\r\n");
      out.write("    <title>Sign up</title>\r\n");
      out.write(" \t<!-- CSS Global -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS Plugins -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction checkpw(){\r\n");
      out.write("    \t\tif(document.getElementById('sign-up__password').value != document.getElementById('sign-up__password_repeat').value){\r\n");
      out.write("    \t\t\talert(\"비밀번호를 확인해주세요!\");\r\n");
      out.write("    \t\t\tdocument.signupForm.repeatPassword.focus();\r\n");
      out.write("    \t\t\treturn false;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\treturn true;\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"body_plain\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- PAGE CONTENT\r\n");
      out.write("    ============================== -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12\">\r\n");
      out.write("          <div class=\"body-plain__title\">\r\n");
      out.write("            <h1 class=\"text-center\">Sign Up</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("      </div> <!-- / .row -->\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-4 col-sm-offset-3 col-md-offset-3 col-lg-offset-4\">\r\n");
      out.write("          <div class=\"body-plain__form\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sign Up form  -->\r\n");
      out.write("            <form role=\"form\" action=\"/review/signup\" method=\"post\" name=\"signupForm\" onsubmit=\"return checkpw()\">\r\n");
      out.write("  \t\t\t  <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"sign-up__name\" class=\"sr-only\">ID</label>\r\n");
      out.write("              \t  <input type=\"text\" class=\"form-control\" id=\"sign-up__id\" name=\"id\" placeholder=\"아이디\" required>\r\n");
      out.write("              \t  <span id=\"idCheckView\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("              \t<label for=\"sign-up__password\" class=\"sr-only\">Password</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"sign-up__password\" name=\"password\" placeholder=\"패스워드\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("              \t <label for=\"sign-up__password_repeat\" class=\"sr-only\">Repeat Password</label>\r\n");
      out.write("                 <input type=\"password\" class=\"form-control\" id=\"sign-up__password_repeat\" name=\"repeatPassword\" placeholder=\"패스워드확인\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("              \t<label for=\"sign-up__name\" class=\"sr-only\">name</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"sign-up__name\" name=\"name\" placeholder=\"이름\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("               \t  <label for=\"sign-up__tel\" class=\"sr-only\">email</label>\r\n");
      out.write("              \t  <input type=\"email\" class=\"form-control\" id=\"sign-up__email\"  name=\"email\"  placeholder=\"이메일\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("             <input type=\"submit\" class=\"btn btn-primary btn-block btn-lg\" value=\"가입완료\"><br>\r\n");
      out.write("             <input type=\"reset\" class=\"btn btn-primary btn-block btn-lg\"  value=\"취소\">\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Sign In link -->\r\n");
      out.write("            <hr />\r\n");
      out.write("            <p>Already a member? <a href=\"/review/login\">Sign into your account.</a></p>\r\n");
      out.write("          </div> <!-- / .body-plain__form -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Footer -->\r\n");
      out.write("          <div class=\"body-plain__footer\">\r\n");
      out.write("            Copyright 2017 <a href=\"http://simpleqode.com/\">Simpleqode.com</a>. All Rights Reserved.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> <!-- / .row -->\r\n");
      out.write("    </div> <!-- / .container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Javascript\r\n");
      out.write("    ============================== -->\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Global -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Plugins -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/scrolltopcontrol.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/wow.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Custom -->\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
