/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-09 08:04:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \t.header{\r\n");
      out.write("  \t\tbackground-image: url(\"resources/img/새싹비빔밥.jpg\");\r\n");
      out.write("  \t}\r\n");
      out.write("  </style>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <meta charset=utf-8>\r\n");
      out.write("    <!--<link rel=\"icon\" href=\"img/favicon.ico\">-->\r\n");
      out.write("\r\n");
      out.write("    <title>Main</title>\r\n");
      out.write(" \t<!-- CSS Global -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS Plugins -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<h1 align=\"center\">Review</h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<ul class=\"topbar-nav topbar-nav_right\">\r\n");
      out.write("\t\t<li><a class=\"navbar-brand\" style=\"color: black;\" href=\"views/member/login.jsp\">Login</a></li>\r\n");
      out.write("\t\t<li><a class=\"navbar-brand\" style=\"color: black;\" href=\"views/member/signup.jsp\">SignUp</a></li>\r\n");
      out.write("\t\t<!-- <li><a class=\"navbar-brand\" style=\"color: black;\" href=\"views/main/main.jsp\">눌르면 임시로 로그인후 메인으로이동</a></li> -->\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- PORTFOLIO\r\n");
      out.write("    ============================== -->\r\n");
      out.write("<div class=\"section section_portfolio section_alt\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-12\" align=\"center\">\r\n");
      out.write("\t\t\t <form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t \t<input type=\"text\" name=\"search\" size=\"80\" placeholder=\"ex)신촌 산토리아\">\r\n");
      out.write("\t\t\t \t<button type=\"submit\" class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t\t\t </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- AUTHORS\r\n");
      out.write("    ============================== -->\r\n");
      out.write("    <div class=\"section section_authors\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-xs-12\">\r\n");
      out.write("            <h1 class=\"section__title\">\r\n");
      out.write("              Developers\r\n");
      out.write("            </h1>\r\n");
      out.write("            <p class=\"section__intro\">\r\n");
      out.write("              Introduce Developers Member\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div> <!-- / .row -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- Author #1 -->\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("            <div class=\"authors__item\">\r\n");
      out.write("              <div class=\"authors__img wow flipInY\" data-wow-offset>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/photo_1.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"authors__content\">\r\n");
      out.write("                <div class=\"authors__title\">John Doe, Designer</div>\r\n");
      out.write("                <div class=\"authors__intro\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu lacus enim. Aliquam eu elit justo. \r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"authors__contact\">\r\n");
      out.write("                  <li class=\"facebook\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"twitter\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"linkedin\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"envelope\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-envelope-o\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Author #2 -->\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("            <div class=\"authors__item\">\r\n");
      out.write("              <div class=\"authors__img wow flipInY\" data-wow-delay=\".2s\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/photo_2.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"authors__content\">\r\n");
      out.write("                <div class=\"authors__title\">Judy Roe, Designer</div>\r\n");
      out.write("                <div class=\"authors__intro\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu lacus enim. Aliquam eu elit justo. \r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"authors__contact\">\r\n");
      out.write("                  <li class=\"facebook\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"twitter\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"linkedin\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"envelope\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-envelope-o\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Author #3 -->\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("            <div class=\"authors__item\">\r\n");
      out.write("              <div class=\"authors__img wow flipInY\" data-wow-delay=\".4s\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/photo_3.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"authors__content\">\r\n");
      out.write("                <div class=\"authors__title\">Richard Doe, Developer</div>\r\n");
      out.write("                <div class=\"authors__intro\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu lacus enim. Aliquam eu elit justo. \r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"authors__contact\">\r\n");
      out.write("                  <li class=\"facebook\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"twitter\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"linkedin\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"envelope\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-envelope-o\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> <!-- / .row -->\r\n");
      out.write("        <!-- Author #3 -->\r\n");
      out.write("        <div class=\"row\" align=\"center\">\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("            <div class=\"authors__item\">\r\n");
      out.write("              <div class=\"authors__img wow flipInY\" data-wow-delay=\".4s\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/photo_3.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"authors__content\">\r\n");
      out.write("                <div class=\"authors__title\">Richard Doe, Developer</div>\r\n");
      out.write("                <div class=\"authors__intro\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu lacus enim. Aliquam eu elit justo. \r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"authors__contact\">\r\n");
      out.write("                  <li class=\"facebook\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"twitter\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"linkedin\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"envelope\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-envelope-o\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Author #3 -->\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-4\">\r\n");
      out.write("            <div class=\"authors__item\">\r\n");
      out.write("              <div class=\"authors__img wow flipInY\" data-wow-delay=\".4s\">\r\n");
      out.write("                <img src=\"\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"authors__content\">\r\n");
      out.write("                <div class=\"authors__title\">SangHyeon Ha, Developer</div>\r\n");
      out.write("                <div class=\"authors__intro\">\r\n");
      out.write("                  LOL. \r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"authors__contact\">\r\n");
      out.write("                  <li class=\"facebook\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"twitter\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"linkedin\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"envelope\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-envelope-o\"></i></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> <!-- / .row -->\r\n");
      out.write("      </div> <!-- /.container -->\r\n");
      out.write("    </div> <!-- / .section -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
